services:
    assistant_rag:
        image: andresdavidarcos/profevardilla:latest
        env_file: .env
        volumes:
        - ./models:/root/.cache/huggingface
        - ./firebase_key.json:/app/qaAssistant/firebase_key.json 
        networks:
        - caddy
        labels:
          caddy: api.profevardilla.xyz
          caddy.reverse_proxy: "{{upstreams 8000}}"
networks:
  caddy:
    external: true