services:
    django-backend:
        build: .
        container_name: profevardilla-backend
        env_file: .env
        volumes:
        - ./models:/root/.cache/huggingface
        ports:
        - "8000:8000"
      
    frontend-proxy:
        image: nginx:latest
        ports:
        - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - django-backend