services:
    django-backend:
        build: .
        container_name: profevardilla-backend
        env_file: .env
        volumes:
        - ./models:/root/.cache/huggingface
        expose:
          - 8000
    frontend-proxy:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
        depends_on: 
            - django-backend
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes: 
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email andretitauro@gmail.com -d api.profevardilla.xyz --agree-tos            